parameters:
#    lectura.example.class: BMN\LecturaBundle\Example

services:
#    lectura.example:
#        class: %lectura.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
