parameters:
#    app_user.example.class: BMN\AppUserBundle\Example

services:
#    app_user.example:
#        class: %app_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
