parameters:
#    nomenclador.example.class: BMN\NomencladorBundle\Example

services:
#    nomenclador.example:
#        class: %nomenclador.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
